""" Movement {{{
" Arrowkey unbinds
noremap Q       <Nop>
noremap <Up>    <Nop>
noremap <Down>  <Nop>
noremap <Left>  <Nop>
noremap <Right> <Nop>

vnoremap <Up>   <Nop>
vnoremap <Down> <Nop>
vnoremap <Left> <Nop>
vnoremap <Right> <Nop>

nnoremap <Up>   <Nop>
nnoremap <Down> <Nop>
nnoremap <Left> <Nop>
nnoremap <Right> <Nop>

" move vertically by visual line
nnoremap j gj
nnoremap k gk
" }}}

""" System {{{
set backspace=2   " Backspace deletes like most programs in insert mode
set backup
set backupdir=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
set backupskip=/tmp/*,/private/tmp/*
set directory=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
set writebackup
set noswapfile    " http://robots.thoughtbot.com/post/18739402579/global-gitignore#comment-458413287
set laststatus=2        " Always display the status line
set autowrite           " Automatically :write before running commands
set autoread            " Reload files changed outside vim
set clipboard=unnamed   " Use the system clipboard

set nocompatible

filetype plugin on
syntax on

set modelines=1         " Check last line of file for mode line
" }}}

""" Longer undo history {{{
set history=700
set undolevels=700
" }}}

""" UI {{{
set showcmd             " display incomplete command
set cursorline          " Highlight current line
set wildmenu            " Show autocomplete options
set lazyredraw          " Prevent redrawing between Macro executions
set showmatch           " Highlight matching characters like { and }
nnoremap gV `[v`]       " Highlight last inserted text
" }}}

""" Folding {{{
set foldenable
set foldlevelstart=10
set foldnestmax=10
nnoremap <space> za     " Space opens/closes current fold
set foldmethod=indent
" }}}

""" Tabs vs Spaces {{{
set tabstop=4
set softtabstop=4
set shiftwidth=4
set shiftround
" }}}

""" Make searching better {{{
set gdefault      " Never have to type /g at the end of search / replace again
set ignorecase    " case insensitive searching (unless specified)
set smartcase
set hlsearch
nnoremap <silent> <leader>, :noh<cr> " Stop highlight after searching
set incsearch
set showmatch
" }}}

""" Easier indentation {{{
vnoremap < <gv
vnoremap > >gv
" }}}

""" Text Width Indicator {{{
set textwidth=100
set wrapmargin=100
set wrap
set linebreak
set nolist
set fo+=l 	" Do not wrap text when typing
set colorcolumn=101
highlight ColorColumn ctermbg=50
" }}}

""" Line Numbers {{{
set number
set numberwidth=5
set rnu
function! ToggleNumbersOn()
    set nu!
    set rnu
endfunction
function! ToggleRelativeOn()
    set rnu!
    set nu
endfunction

autocmd FocusLost * call ToggleRelativeOn()
autocmd FocusGained * call ToggleRelativeOn()
autocmd InsertEnter * call ToggleRelativeOn()
autocmd InsertLeave * call ToggleRelativeOn()
" }}}

""" Shortcuts {{{
inoremap jk <esc>       " jk functions as escape in insert mode
nnoremap <C-O> O<esc>
noremap <C-o> o<esc>

" Leader Shortcuts
let mapleader=","       " Leader is comma
nnoremap <leader>u :GundoToggle<CR>

""" Force Markdown
autocmd BufNewFile,BufReadPost *.md set filetype=markdown
" }}}

""" LaTeX Shortcuts {{{

" (Thanks Luke Smith (www.lukesmith.xyz))

autocmd BufNewFile,BufReadPost *.tex set filetype=tex

autocmd FileType tex inoremap ;em \emph{}<Space><Esc>T{i
autocmd FileType tex inoremap ;bf \textbf{}<Space><Esc>T{i
autocmd FileType tex inoremap ;it \textit{}<Space><Esc>T{i
autocmd FileType tex inoremap ;ct \citet{}<Space><Esc>T{i
autocmd FileType tex inoremap ;ol \begin{enumerate}<Enter>\end{enumerate}<Esc>kA\item<Space>
autocmd FileType tex inoremap ;ul \begin{itemize}<Enter>\end{itemize}<Esc>kA\item<Space>
autocmd FileType tex inoremap ;beg \begin{%DELRN%}<Enter>\end{%DELRN%}<Esc>0fR:MultipleCursorsFind<Space>%DELRN%<Enter>c
" }}}

"""  Plugins {{{

" Ctrl-P Settings
let g:ctrlp_match_window = 'bottom,order:ttb'
let g:ctrlp_switch_buffer = 0
let g:ctrlp_working_path_mode = 0

" vim-ledger
autocmd BufNewFile,BufRead *.ledger set filetype=ledger

execute pathogen#infect()

let g:airline_theme='base16_grayscale' " airline statusbar theme
let g:syntastic_mode_map = {'mode':'passive', 'active_filetypes':[], 'passive_filetypes':[]}

set runtimepath^=~/.vim/bundle/ctrlp.vim
" }}}

" vim:foldmethod=marker:foldlevel=0
